# Generated by Django 2.2 on 2019-04-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('suburb', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=4)),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
    ]
