# Generated by Django 2.2 on 2019-04-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VICHealth_app', '0002_auto_20190427_0607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
