# Generated by Django 2.2 on 2019-04-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VICHealth_app', '0005_auto_20190428_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='club',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='place_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='postcode',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='club',
            name='state',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='club',
            unique_together=set(),
        ),
    ]
