# Generated by Django 2.2 on 2019-04-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VICHealth_app', '0007_auto_20190428_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='suburb',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
